import { useRef, useEffect } from 'react';
import { useCursor } from '../hooks/useCursor';
import { distance } from '../utils/helpers';

const Scene8 = ({ active, onChoice }) => {
  const canvasRef = useRef(null); const { position } = useCursor();
  useEffect(() => {
    const canvas = canvasRef.current; if (!canvas) return; const ctx = canvas.getContext('2d'); let animationId; let time = 0;
    const resize = () => { canvas.width = window.innerWidth; canvas.height = window.innerHeight; }; resize(); window.addEventListener('resize', resize);
    const portals = [ { x: canvas.width * 0.35, y: canvas.height * 0.5, label: 'RETURN', radius: 80 }, { x: canvas.width * 0.65, y: canvas.height * 0.5, label: 'ENTER', radius: 80 } ];
    const draw = () => { time += 0.02; ctx.clearRect(0, 0, canvas.width, canvas.height); ctx.strokeStyle = 'rgba(0, 240, 255, 0.2)'; ctx.lineWidth = 1; ctx.beginPath(); ctx.moveTo(0, canvas.height * 0.7); ctx.lineTo(canvas.width, canvas.height * 0.7); ctx.stroke(); portals.forEach((portal, i) => { const dist = distance(portal.x, portal.y, position.x, position.y); const isHovered = dist < portal.radius; const pulse = Math.sin(time * 2) * 10; const gradient = ctx.createRadialGradient(portal.x, portal.y, 0, portal.x, portal.y, portal.radius + pulse); gradient.addColorStop(0, isHovered ? 'rgba(0, 240, 255, 0.4)' : 'rgba(0, 240, 255, 0.2)'); gradient.addColorStop(0.7, isHovered ? 'rgba(0, 240, 255, 0.2)' : 'rgba(0, 240, 255, 0.1)'); gradient.addColorStop(1, 'rgba(0, 240, 255, 0)'); ctx.fillStyle = gradient; ctx.beginPath(); ctx.arc(portal.x, portal.y, portal.radius + pulse, 0, Math.PI * 2); ctx.fill(); ctx.strokeStyle = isHovered ? 'rgba(0, 240, 255, 0.8)' : 'rgba(0, 240, 255, 0.4)'; ctx.lineWidth = 2; ctx.beginPath(); ctx.arc(portal.x, portal.y, portal.radius, 0, Math.PI * 2); ctx.stroke(); ctx.beginPath(); ctx.arc(portal.x, portal.y, portal.radius * 0.7, 0, Math.PI * 2); ctx.stroke(); ctx.font = '16px "Orbitron"'; ctx.fillStyle = isHovered ? 'rgba(0, 240, 255, 1)' : 'rgba(0, 240, 255, 0.6)'; ctx.textAlign = 'center'; ctx.fillText(portal.label, portal.x, portal.y + 5); ctx.font = '10px "JetBrains Mono"'; ctx.fillStyle = 'rgba(0, 240, 255, 0.4)'; ctx.fillText(i === 0 ? 'STATIC REALITY' : 'EDITABLE LAYER', portal.x, portal.y + 120); }); for (let i = 0; i < 50; i++) { const startX = Math.random() * canvas.width; const endX = canvas.width / 2 + Math.sin(time + i) * 50; ctx.strokeStyle = `rgba(0, 240, 255, ${Math.random() * 0.1})`; ctx.beginPath(); ctx.moveTo(startX, canvas.height); ctx.lineTo(endX, 0); ctx.stroke(); } animationId = requestAnimationFrame(draw); };
    draw(); return () => { cancelAnimationFrame(animationId); window.removeEventListener('resize', resize); };
  }, [position]);
  return (<div className="scene-container" style={{ background: 'var(--bg-primary)' }}><canvas ref={canvasRef} /><div className="scene-content flex flex-col justify-center items-center min-h-screen px-8"><div className="text-center mb-16"><h2 className="font-display text-2xl md:text-4xl text-cyan-400 mb-4">AUTHORIZATION REQUIRED</h2><p className="text-sm text-gray-500">Choose your path forward</p></div><div className="flex gap-32"><button onClick={() => onChoice?.('return')} className="font-display px-8 py-4 border border-cyan-400/30 text-cyan-400 hover:bg-cyan-400/10 transition-all duration-300 focus:outline-none focus:ring-2 focus:ring-cyan-400">RETURN TO STATIC REALITY</button><button onClick={() => onChoice?.('enter')} className="font-display px-8 py-4 bg-cyan-400/20 border border-cyan-400 text-cyan-400 hover:bg-cyan-400/30 transition-all duration-300 focus:outline-none focus:ring-2 focus:ring-cyan-400">ENTER EDITABLE LAYER</button></div></div></div>);
};
export default Scene8;