import { useRef, useEffect } from 'react';
import { useCursor } from '../hooks/useCursor';
import { distance, lerp } from '../utils/helper';

const Scene5 = ({ active }) => {
  const canvasRef = useRef(null); const nodesRef = useRef([]); const cursorsRef = useRef([]); const { position } = useCursor();
  useEffect(() => {
    const canvas = canvasRef.current; if (!canvas) return; const ctx = canvas.getContext('2d'); let animationId; let time = 0;
    const resize = () => { canvas.width = window.innerWidth; canvas.height = window.innerHeight; }; resize(); window.addEventListener('resize', resize);
    if (nodesRef.current.length === 0) { for (let i = 0; i < 150; i++) nodesRef.current.push({ x: Math.random() * canvas.width, y: Math.random() * canvas.height, baseX: Math.random() * canvas.width, baseY: Math.random() * canvas.height, radius: Math.random() * 2 + 1, phase: Math.random() * Math.PI * 2 }); cursorsRef.current = [{ offset: { x: 0, y: 0 } }, { offset: { x: 100, y: -50 } }, { offset: { x: -100, y: 50 } }, { offset: { x: 50, y: 100 } }, { offset: { x: -50, y: -100 } }]; }
    const cursorPositions = cursorsRef.current.map(() => ({ ...position }));
    const draw = () => { time += 0.02; ctx.clearRect(0, 0, canvas.width, canvas.height); cursorsRef.current.forEach((cursor, i) => { cursorPositions[i] = { x: lerp(cursorPositions[i].x, position.x + cursor.offset.x, 0.1), y: lerp(cursorPositions[i].y, position.y + cursor.offset.y, 0.1) }; }); nodesRef.current.forEach(node => { const shake = Math.sin(time * 3 + node.phase) * 5; node.x = node.baseX + shake; node.y = node.baseY + shake; let nearestDist = Infinity; cursorPositions.forEach(cp => { const d = distance(node.x, node.y, cp.x, cp.y); if (d < nearestDist) nearestDist = d; }); if (nearestDist < 150) { const glow = (150 - nearestDist) / 150; const gradient = ctx.createRadialGradient(node.x, node.y, 0, node.x, node.y, 15); gradient.addColorStop(0, `rgba(0, 240, 255, ${glow * 0.5})`); gradient.addColorStop(1, 'rgba(0, 240, 255, 0)'); ctx.fillStyle = gradient; ctx.beginPath(); ctx.arc(node.x, node.y, 15, 0, Math.PI * 2); ctx.fill(); } ctx.fillStyle = `rgba(0, 240, 255, ${0.3 + Math.random() * 0.2})`; ctx.beginPath(); ctx.arc(node.x, node.y, node.radius, 0, Math.PI * 2); ctx.fill(); }); cursorPositions.forEach(cp => { const gradient = ctx.createRadialGradient(cp.x, cp.y, 0, cp.x, cp.y, 40); gradient.addColorStop(0, 'rgba(0, 240, 255, 0.6)'); gradient.addColorStop(1, 'rgba(0, 240, 255, 0)'); ctx.fillStyle = gradient; ctx.beginPath(); ctx.arc(cp.x, cp.y, 40, 0, Math.PI * 2); ctx.fill(); ctx.strokeStyle = 'rgba(0, 240, 255, 0.8)'; ctx.lineWidth = 1; ctx.beginPath(); ctx.moveTo(cp.x - 15, cp.y); ctx.lineTo(cp.x + 15, cp.y); ctx.moveTo(cp.x, cp.y - 15); ctx.lineTo(cp.x, cp.y + 15); ctx.stroke(); }); animationId = requestAnimationFrame(draw); };
    draw(); return () => { cancelAnimationFrame(animationId); window.removeEventListener('resize', resize); };
  }, [position]);
  return (<div className="scene-container" style={{ background: 'var(--bg-primary)' }}><canvas ref={canvasRef} /><div className="scene-content flex flex-col justify-center items-center min-h-screen px-8"><div className="text-center"><h2 className="font-display text-3xl md:text-5xl text-cyan-400 mb-6" style={{ animation: active ? 'flicker 0.1s infinite' : 'none', textShadow: '0 0 30px rgba(0, 240, 255, 0.8)' }}>MULTIPLE INSTANCES DETECTED</h2><p className="font-display text-xl md:text-3xl text-red-400" style={{ animation: active ? 'pulse 1s infinite' : 'none' }}>IDENTITY NO LONGER SINGULAR</p></div></div></div>);
};
export default Scene5;